apiVersion: v1
kind: Service
metadata:
  name: hw-svc
spec:
  ports:
  - port: 8888
    nodePort: 31001
    # 30000-32767
    targetPort: nginxport
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
